import type { Metadata } from "next";
import { Inter } from "next/font/google";
import favicon from "@/assets/images/favicon.jpg";
import Header from "@/components/header";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/components/footer";

import "@/assets/scss/global.scss";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"/>
      <link rel="icon" href="../assets/images/fav.ico" sizes="any" />
      </head>
      <body className={inter.className}>
      <div className='page_layout_wrapper'>
      <Header/>
      {children}
    
      </div>
      <Footer/> 
      
      </body>
    
    </html>
  );
}
